### ISSUE TITLE
Incoherent behavior when there is an exception

### ISSUE THREAD

**Issue by owford** [marcus-oscarsson/pyqtconsole#46]
Using the Python REPL, I run 2 snippets :

```
from pyqtconsole.console import PythonConsole
from PyQt5.QtWidgets import QApplication
app = QApplication([])
console = PythonConsole()
console.show()
console.eval_queued()
```

```
from pyqtconsole.console import PythonConsole
from PyQt5.QtWidgets import QApplication
def main():
    console = PythonConsole()
    console.show()
    console.eval_queued()

app = QApplication([])
main()
```

Both work correctly, but when there is an exception in the evaluated code :
- the console widget is closed in the 2nd snippet.
- it keeps working in the 1st snippet.

I can and will keep a reference to the console, but that behavior doesn't seem normal IMHO.

**Comment by coldfix** [comment]
Both snippets behaving differently is not all to surprising, due to the different lifetimes of the objects:

- in the first case, you store a global reference to the console widget, i.e. the `console` variable at the level of the python REPL. This will keep the object alive and displayed, even if some code raises an exception
-  in the second case, the only reference to the console widget is stored at the function scope of your `main`. If there is now an exception that causes the `main` function to be left, the reference will be relieved and PyQt may decide to destroy the object and close the window as a consequence

**Comment by coldfix** [comment]
It should be pretty much the same, if you replace `PythonConsole` here by `QWidget`, `QTextEdit` or any other normal kind of widget, and generate an exception that exits main.

**Comment by coldfix** [comment]
Hm, sorry, I didn't properly read "*Both work correctly, but when there is an exception in the evaluated code [...]*".

You are right that exceptions in the evaluated code within the shell should not propagate outward into your application level. Can you provide example code?

Btw both snippets, should also call `app.exec_()`.

**Comment by owford** [comment]
Regarding the lifetimes of the objects :
Notice that my main function returns immediately. I did the test with a `QWidget`, and yes, the widget is closed immediately.
So I guess in the case of PythonConsole it works (until there's an exception) because of the internals of `eval_queued()`. But I shouldn't rely on that behavior.

**Comment by owford** [comment]
I don't know if the exception is propagated, but it's printed on stderr. Is that normal ? I would expect to see it in the widget.
The example code is simply either of the snippets in REPL and typing `a` in the console.

```
>>> main()
>>> Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.5/site-packages/pyqtconsole/interpreter.py", line 46, in exec_
    result = eval(code, self.locals)
  File "<input>", line 1, in <module>
NameError: name 'a' is not defined
```

I don't need to call `app.exec_()` because the Python REPL calls `processEvents` regularly.

**Comment by coldfix** [comment]
for me, it's printed within the widget. Which version of pyqtconsole/python/PyQt or PySide are you using? Or are you using this within IDLE or another environment?

I suspect that this is due to the way `disabled_excepthook()` is setup, there may be a different sys.excepthook in your case, but will have to check up on this later.

Best, Thomas

**Comment by owford** [comment]
I have Ubuntu 16.04, Python 3.5.2, pyqtconsole 1.1.5

```
>>> from sip import SIP_VERSION_STR
>>> from PyQt5.Qt import PYQT_VERSION_STR
>>> from PyQt5.QtCore import QT_VERSION_STR
>>> SIP_VERSION_STR, PYQT_VERSION_STR, QT_VERSION_STR
('4.17', '5.5.1', '5.5.1')
```

I get this behavior both when using the REPL from a terminal and when running `python3 foo.py`.

**Comment by owford** [comment]
Oh. Based on what you said, this looks like the culprit, right ?
```
>>> import sys
>>> sys.excepthook
<function apport_excepthook at 0x7fa11e1ece18>
>>> help(sys.excepthook)
Help on function apport_excepthook in module apport_python_hook:

apport_excepthook(exc_type, exc_obj, exc_tb)
    Catch an uncaught exception and make a traceback.
```
