### ISSUE TITLE
console does not react to Enter key

### ISSUE THREAD

**Issue by toonhuysmans** [marcus-oscarsson/pyqtconsole#9]
I am running pyqtconsole 1.0 with PyQt4 and Python 2.7.12. The console shows up fine and I can type in text but the console does not react to the enter key, so I can not execute any commands.

**Comment by toonhuysmans** [comment]
OK I fixed the problem. I did not properly attach a QTimer to PythonConsole.repl_nonblock. The timer went out of scope soon after creation, so there was no updating happening. Fixed it by making the timer a class variable.

**Comment by marcus-oscarsson** [comment]
Hi @toonhuysmans 

:) okey, happy that you were able to solve your problem

Marcus

**Comment by cudmore** [comment]
Having the same problem here. I am running the example with gevent. The example runs fine and I get am iPython terminal window which starts with [0]. Entering `print(1)` then the `enter` key goes to the next line in the terminal rather than evaluating the command? If I enter an invalid command, the terminal does print the error on pressing return?

macOS 10.12.6 Sierra
Python 3.7.3
PyQt5==5.13.1
PyQt5-sip==12.7.0
PyQtChart==5.13.0
pyqtconsole==1.1.3

**Comment by coldfix** [comment]
Hi, @cudmore 

I can confirm this happens. I believe the issue is due to gevent not being scheduled to run its greenlets due to the application spending its time with qt message processing in `app.exec_()` (which doesn't know about gevent stuff).

One would need to add to the example some means of letting gevent run every once in a while, e.g. in a idle timer, see e.g. here https://stackoverflow.com/questions/4628348/using-pyqt-with-gevent

**Comment by marcus-oscarsson** [comment]
@coldfix thanks cold fix for the fast reposne, @cudmore did it solve your issue ?

**Comment by coldfix** [comment]
I posted a fix to the example in #28 that seems to work for me. A bigger application would probably have their own interoperability code that is better suited to their needs.

**Comment by marcus-oscarsson** [comment]
@coldfix thanks, it's merged. Yes you are right, but it's fine as an example
